kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-mutating-webhook
webhooks:
  - name: mutating-webhook.openpolicyagent.org
    rules:
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      service:
        namespace: opa
        name: opa
      caBundle:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVR1FPdWhncWthdHJEeThXTGxzcE41bWh6VWNzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSXhNRGd4TnpFeU1EYzBNbG9ZRHpJeQpPVFV3TmpBeU1USXdOelF5V2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURNMUlDYTBab3o5ZVNVT1JQd0tlS2J5ejZtT1BRQjZHS2MKeG1wSlozTnBwNTV4OFcxc1U4OVh4V1Z0Z3lVVHR6azFVSWNqQStUUmphUUh1UEd3bE91dzBDRGQvb3g4N3NxUwpiNzFIWWJGdmtzR3hCS05YamF4eWdHVWhwa0cxUUJlYzZQYjlyY1hCdTJ4VVV6V0V3azJZdUpRWkJEK1hLSFpZCmNRRVJXczRTRUxXK2xaRW5HbEx0Y1BMUGdXbk52M0ZiVFJlbUVrdm1RcC81K0Y1dW5kS2VqTnBhWUprcnpPcUgKWkJzMkxzYzBYN0ZwbXpFcWt3S2NlcUh6OVdSRlVVcE8vWVlFNkU2KzBGSjRxUng4dWUvbGpaNEFBRXRGMTBqZwpkSGpKWEFXUlRaU05uaktOTzlxcXFwZEF6T0doaGE3QzZ6eGloamhwSGxUMjNlRnJDY2J4QWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCVEw4dnR1ZmtwOGh2WGMyTFJKQVVnancrcDgvREFmQmdOVkhTTUVHREFXZ0JUTDh2dHUKZmtwOGh2WGMyTFJKQVVnancrcDgvREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFDZDBtaVZScjJnNTNudWgxYU9nRzJyOXMwQmI5Z1lZOXpZaHlNbW5EZmZIam5mc25DaGNudUh3b294CnlqVWZ6dmtHbHkvV2pLR21CbzdEcnVZNHNFZnJ4K2FRMklzc21Hdi9DREE5OUgzVlA4VURmUjlyT0tTT2hKSnAKVXBaY056NVF6MU1ZaDNJdkVzc2VGdnBvNHl3UUI4eWdJdnliMGVuaWJXREU2eVFCcS90a3U3TlNMUDVkTGdyZgo5YnZDL1F1U1BiK0dIMmJ0bXJzbUxROHdHVWVJNVFFOGdlYTJiNkptTWxPTXBmK0FJelVUR3JicnlGc1JXZXNVCjVNQm1haXpVc3U2ZjYzSlphMjZMVTlwWkZ6MDFaUFQyOXc1Um1RQ3FxN2ZmQk9Db1BFcXZKZml4bHFLQ0NtVDYKVGFtWm5tTnkyRHIzVHhadjlydXB6aXgxbEJBQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
