kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-mutating-webhook
webhooks:
  - name: mutating-webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore
    rules:
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVZmVCSzMxM0V3akpMM3NHejhiU3lKNTU3VUFNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSXhNVEF3TnpFME5EZ3lObG9ZRHpJeQpPVFV3TnpJek1UUTBPREkyV2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURWNHg4MkxWclFZbWdMZ2hyZitLbktsQ1JYLzN4OS9ZMU0Kb1ZiNUZMWHllL3NpZVpBZk1IOUJNdXArL1VRczJGV0N1VVN6SXNvMVpBckk4OGJUblNnUXIrMzI0anVndWRMOAo4bzRYdGo1ZWF1cFVRaDNHRmw4SWRmamY5bUhqSmdvODFwejh1UVNwdUJMWkdsbjRqa0o3S1VZODlhb2EzQ3pPCnFNMXcxanV2aDM2bVpYQmlyb0dDem5oWmRaNXdmemt4TWM0NG9FalFhTHA4Uk5qN3IvWlNYTmsxWHpkcjFTNjcKMjkzelBIRms3Um9ORkpia3dDc3ZwT3ovZERBUWUwa1E2NlVWUzVrc1BDY0RaNVl4VnpiUms2ZGxmWDJEYXZXeApNT2F0Y1dleDRjbzRGY2VUTHdzL1Y0T2Z5aHJzcDhlc2hUeC9vc01uVnZFNDJTSWFOVUM3QWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCUk9nZWtOUEtTWDRVR1RGRnlwa1pFYXpJSUFNREFmQmdOVkhTTUVHREFXZ0JST2dla04KUEtTWDRVR1RGRnlwa1pFYXpJSUFNREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFBaXFSSG1JZW1vTG85U2pxZzQ1QmpaRzhxZ05mT01mVkpBQ01qSytUUEJYNG5IUEFVTURCODNiNVRNCkZQNHFiK2RZMVhOWTlXRjhDbkFFNm5BQmRLbEVBZzF4L2xKN0ZnU2VRYjQvZXhTcmNlK0FsRnlMT1JlWHNBeXoKMzBRQTQ0UU5yazhvN2RxNkIwRkZMNE5PeFBBL2t0bG1yTEZKV3lPZ2VIRTBhZDNhQzZ4N25Wb1pRdk9RMWlCMwpyZ3lyamkxWmQ1elUvY1ZLWExFTjBzWmNFcW5DMHpVWFJMTEZPTkNGSzgxdk85SDE3VjI1OHhyUnp5YkFKUjlaClJXSVpiNEZScWl0eDVYb3EydFRWWTV4YzI0ZVMveU9RV3MxQjNMbzg1Q2taZzdPNUpMUWRtSWM1aDIyL1RsdzEKdkJVeFhnVzRIZ21qS3RLc1YvQjFwTndrNWRPMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: opa
        name: opa
